### ISSUE TITLE
ValueError in `position_on_edge` when running on large network

### ISSUE THREAD

**Issue by falkecarlsen** [d610f20/random-activitygen-py#36]
Running `time python randomActivityGen.py -n in/aalborg_metro.net.xml -s in/aalborg_metro.stat.xml -o /out/aalborg_metro.stat.xml --verbose --display` on OSM downloaded map of Aalborg metropolitan area.

```
Traceback (most recent call last):
  File "randomActivityGen.py", line 160, in <module>
    main()
  File "randomActivityGen.py", line 147, in main
    setup_bus_stops(net, stats, int(args["--bus-stop.distance"]), int(args["--bus-stop.k"]))
  File "randomActivityGen.py", line 92, in setup_bus_stops
    for i, busstop in enumerate(bus_stop_generator(edges, min_distance, min_distance*2, k, seeds=seed_bus_stops)):
  File "/home/user/projects/random-activitygen-py/bus.py", line 80, in bus_stop_generator
    point = next(filter(
  File "/home/user/projects/random-activitygen-py/utility.py", line 187, in firstn
    yield next(gen)
  File "/home/user/projects/random-activitygen-py/bus.py", line 24, in _road_point_generator
    pos = position_on_edge(road, remaining)
  File "/home/user/projects/random-activitygen-py/utility.py", line 126, in position_on_edge
    for coord1, coord2 in (edge.getShape()[i:i + 2] for i in range(0, int(len(edge.getShape())), 2)):
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by falkecarlsen** [comment]
Map is 186MB, so I will supply it on demand if required for reproduction.

**Comment by falkecarlsen** [comment]
During a run without busstops which prompted this issue, the display_network function threw these errors:
```
INFO     Displaying network as image of max: 1000 x 1000 dimensions
ERROR    [position_on_edge] Got ValueError on (40484.520000000004, 42041.240000000005), (40517.869999999995, 42144.05)
ERROR    [position_on_edge] Got ValueError on (40484.520000000004, 42041.240000000005), (40517.869999999995, 42144.05)
ERROR    [position_on_edge] Got ValueError on (6865.84, 11857.09), (6878.72, 11854.27)
ERROR    [position_on_edge] Got ValueError on (17799.975, 8888.119999999999), (17761.605, 8905.815)
ERROR    [position_on_edge] Got ValueError on (9537.54, 6328.135), (9538.279999999999, 6316.125)
ERROR    [position_on_edge] Got ValueError on (9374.41, 5488.76), (9363.23, 5483.18)
ERROR    [position_on_edge] Got ValueError on (13667.150000000001, 11315.91), (13683.154999999999, 11311.275000000001)
ERROR    [position_on_edge] Got ValueError on (5308.72, 18939.23), (5263.89, 18948.32)
DEBUG    STREAM b'IHDR' 16 13
DEBUG    STREAM b'IDAT' 41 1216
```
